import { $, readStorage, saveStorage, showToast } from './ui.js';
const melodies=[{name:'青色回忆',notes:[64,67,71,74,71,67,69,67,64,62,64,67,69,67,62,59]},{name:'千禧漫游',notes:[60,64,67,72,71,67,64,62,65,69,72,76,74,72,69,67]},{name:'星光信号',notes:[69,72,76,79,76,74,72,69,67,71,74,76,74,71,67,64]}];
let localTracks=[],audioContext,output,audio,track=0,playing=false,muted=false,elapsed=0,startedAt=0,tickTimer,nextNoteAt=0;
const activeNotes=new Set(), trackList=()=>localTracks.length?localTracks:melodies, currentTrack=()=>trackList()[track]||melodies[0], duration=()=>audio?.duration&&Number.isFinite(audio.duration)?audio.duration:120;
const shellToggle=document.createElement('button');shellToggle.id='cassette-shell-toggle';shellToggle.type='button';shellToggle.className='caption-button icon-button';shellToggle.textContent='◈';shellToggle.setAttribute('aria-label','切换透明磁带外壳');shellToggle.title='透明磁带外壳';shellToggle.setAttribute('aria-pressed',String(readStorage('web-surfer-transparent-cassette',false)===true));
const titleActions=document.createElement('div');titleActions.className='titlebar-actions';const likeButton=$('#radio-like');likeButton.parentNode.insertBefore(titleActions,likeButton);titleActions.append(shellToggle,likeButton);
if(shellToggle.getAttribute('aria-pressed')==='true')$('#cassette').classList.add('transparent-shell');
const formatTime=s=>{const t=Math.max(0,Math.floor(s));return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;};
function timeNow(){return playing?(audio?audio.currentTime:Math.min(120,elapsed+(audioContext.currentTime-startedAt))):elapsed;}
function updatePlayer(){const time=Math.min(duration(),timeNow()),current=currentTrack();$('#radio-time').textContent=formatTime(time);$('#seek').max=String(Math.max(1,Math.floor(duration())));$('#seek').value=String(Math.floor(time));$('#track-name').textContent=`0${track+1} · ${current.name}${current.src?' / 本地 MP3':' / 原创合成旋律'}`;$('#radio-play').textContent=playing?'Ⅱ':'▶';$('#radio-play').setAttribute('aria-label',playing?'暂停电台':'播放电台');$('#cassette').classList.toggle('playing',playing);const progress=Math.min(1,time/Math.max(1,duration()));$('#cassette').style.setProperty('--left-pack',String(1-progress*.35));$('#cassette').style.setProperty('--right-pack',String(.65+progress*.35));$('#tape-status').textContent=playing?'PLAY':time>0?'PAUSE':'STOP';$('#radio-play').setAttribute('aria-pressed',String(playing));}
function stopNotes(){activeNotes.forEach(note=>{try{note.stop();}catch{}});activeNotes.clear();}
function scheduleNote(midi,time,noteDuration,volume,type){const oscillator=audioContext.createOscillator(),envelope=audioContext.createGain();oscillator.type=type;oscillator.frequency.value=440*2**((midi-69)/12);envelope.gain.setValueAtTime(0,time);envelope.gain.linearRampToValueAtTime(volume,time+.025);envelope.gain.exponentialRampToValueAtTime(.001,time+noteDuration);oscillator.connect(envelope).connect(output);oscillator.start(time);oscillator.stop(time+noteDuration+.03);activeNotes.add(oscillator);oscillator.onended=()=>{activeNotes.delete(oscillator);oscillator.disconnect();envelope.disconnect();};}
function tick(){if(!playing)return;if(audio){if(audio.ended||timeNow()>=duration()-.05){changeTrack(1);return;}updatePlayer();return;}if(timeNow()>=120){changeTrack(1);return;}while(nextNoteAt<audioContext.currentTime+.12){const index=Math.floor((elapsed+nextNoteAt-startedAt)/.3),notes=currentTrack().notes;scheduleNote(notes[((index%notes.length)+notes.length)%notes.length],nextNoteAt,.42,.13,'triangle');if(index%4===0)scheduleNote(notes[0]-24,nextNoteAt,.9,.12,'sine');nextNoteAt+=.3;}updatePlayer();}
function setupAudio(source){if(audio)audio.pause();audio=new window.Audio(source);audio.preload='metadata';audio.volume=muted?0:.7;audio.addEventListener('ended',()=>{if(playing)changeTrack(1);});audio.addEventListener('error',()=>{if(playing){pause();showToast('本地音乐暂时无法播放，请检查文件格式。');}});audio.addEventListener('loadedmetadata',updatePlayer);}
async function play(){if(playing)return;const current=currentTrack();try{if(current.src){if(!audio||audio.src!==new URL(current.src,location.href).href)setupAudio(current.src);if(elapsed>=duration())elapsed=0;audio.currentTime=elapsed;await audio.play();playing=true;}else{if(!audioContext){const AudioContext=window.AudioContext||window.webkitAudioContext;audioContext=new AudioContext();output=audioContext.createGain();output.gain.value=muted?0:.6;output.connect(audioContext.destination);}await audioContext.resume();if(elapsed>=120)elapsed=0;startedAt=audioContext.currentTime;nextNoteAt=startedAt+.03;playing=true;}tickTimer=setInterval(tick,80);tick();}catch{showToast('当前浏览器无法启动音频，请检查声音权限后重试。');}}
function pause(reset=false){elapsed=reset?0:Math.min(duration(),timeNow());playing=false;clearInterval(tickTimer);stopNotes();if(audio){audio.pause();if(reset)audio.currentTime=0;}updatePlayer();}
function changeTrack(direction){const wasPlaying=playing;pause(true);track=(track+direction+trackList().length)%trackList().length;updatePlayer();if(wasPlaying)play();}
$('#radio-play').addEventListener('click',()=>playing?pause():play());$('#radio-stop').addEventListener('click',()=>pause(true));$('#radio-next').addEventListener('click',()=>changeTrack(1));$('#radio-previous').addEventListener('click',()=>changeTrack(-1));
$('#radio-mute').addEventListener('click',()=>{muted=!muted;if(output)output.gain.setValueAtTime(muted?0:.6,audioContext.currentTime);if(audio)audio.volume=muted?0:.7;$('#radio-mute').textContent=muted?'×':'♫';$('#radio-mute').setAttribute('aria-pressed',String(muted));$('#radio-mute').setAttribute('aria-label',muted?'取消静音':'静音');});
shellToggle.addEventListener('click',()=>{const transparent=!$('#cassette').classList.contains('transparent-shell');$('#cassette').classList.toggle('transparent-shell',transparent);shellToggle.setAttribute('aria-pressed',String(transparent));saveStorage('web-surfer-transparent-cassette',transparent);});
$('#seek').addEventListener('input',event=>{const value=Number(event.target.value),wasPlaying=playing;pause();elapsed=value;updatePlayer();if(wasPlaying)play();});let radioLiked=readStorage('web-surfer-radio-liked',false)===true;function updateLike(){$('#radio-like').textContent=radioLiked?'♥':'♡';$('#radio-like').setAttribute('aria-pressed',String(radioLiked));}$('#radio-like').addEventListener('click',()=>{radioLiked=!radioLiked;saveStorage('web-surfer-radio-liked',radioLiked);updateLike();});window.addEventListener('pagehide',()=>pause());
fetch('/api/radio',{cache:'no-store'}).then(response=>response.ok?response.json():null).then(data=>{if(data?.tracks?.length){localTracks=data.tracks;track=0;updatePlayer();}}).catch(()=>{});updateLike();updatePlayer();
