import test from 'node:test';
import assert from 'node:assert/strict';
import { categoryNodes, upsertSite, deleteSites, moveSites, deleteCategory } from '../management-data.js';
import { validateNavigation, validatePageContent } from '../navigation-data.js';
function fixture(){return{navigation:{version:1,source:{name:'测试',url:'https://example.com'},categories:[{id:'parent',name:'一级',sites:[{id:'a',name:'A',url:'https://a.example.com',description:''}],children:[{id:'child',name:'二级',sites:[{id:'b',name:'B',url:'https://b.example.com',description:''}]}]},{id:'other',name:'其他',sites:[{id:'c',name:'C',url:'https://c.example.com',description:''}]}]},content:{hot:{title:'推荐',siteIds:['a','b','c']},featured:{title:'精选',items:[]},friends:[]}};}
function validate(d){validateNavigation(d.navigation);validatePageContent(d.content,d.navigation.categories);}
test('editing a website in place preserves its order and moving it removes the original record',()=>{const d=fixture();const site={...d.navigation.categories[0].sites[0],name:'修改后的 A'};upsertSite(d,site,'parent');assert.equal(d.navigation.categories[0].sites[0].name,'修改后的 A');upsertSite(d,site,'child');assert.equal(d.navigation.categories[0].sites.length,0);assert.deepEqual(d.navigation.categories[0].children[0].sites.map(s=>s.id),['b','a']);assert.deepEqual(d.content.hot.siteIds,['a','b','c']);validate(d);});
test('bulk deletion affects parent and child records and cleans recommendations',()=>{const d=fixture();deleteSites(d,new Set(['a','b']));assert.equal(d.navigation.categories[0].sites.length,0);assert.equal(d.navigation.categories[0].children[0].sites.length,0);assert.deepEqual(d.content.hot.siteIds,['c']);validate(d);});
test('bulk move keeps records unique, preserves recommendations and uses real destination objects',()=>{const d=fixture();moveSites(d,new Set(['a','b']),'other');assert.deepEqual(d.navigation.categories[1].sites.map(s=>s.id),['c','a','b']);assert.equal(d.navigation.categories[0].sites.length,0);assert.equal(d.navigation.categories[0].children[0].sites.length,0);assert.equal(d.content.hot.siteIds.length,3);moveSites(d,new Set(['a','b']),'other');assert.equal(categoryNodes(d).flatMap(c=>c.sites).length,3);validate(d);});
test('deleting a parent removes all descendants and their recommendation references',()=>{const d=fixture();deleteCategory(d,'parent');assert.deepEqual(d.navigation.categories.map(c=>c.id),['other']);assert.deepEqual(d.content.hot.siteIds,['c']);validate(d);});
test('deleting a child leaves its parent and sibling records intact',()=>{const d=fixture();deleteCategory(d,'child');assert.equal(d.navigation.categories[0].children.length,0);assert.equal(d.navigation.categories[0].sites.length,1);assert.deepEqual(d.content.hot.siteIds,['a','c']);validate(d);});
test('invalid move targets fail before modifying any source records',()=>{const d=fixture(),before=structuredClone(d);assert.throws(()=>moveSites(d,new Set(['a']),'missing'));assert.deepEqual(d,before);});
